WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 570, in <module>
    main(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 295, in main
    misc.init_distributed_mode(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/util/misc.py", line 248, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

| distributed init (rank 3): env://, gpu 3
| distributed init (rank 1): env://, gpu 1
| distributed init (rank 2): env://, gpu 2
| distributed init (rank 0): env://, gpu 0
Traceback (most recent call last):
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 570, in <module>
    main(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 295, in main
    misc.init_distributed_mode(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/util/misc.py", line 248, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 570, in <module>
    main(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 295, in main
    misc.init_distributed_mode(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/util/misc.py", line 248, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 570, in <module>
    main(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/main_node2node.py", line 295, in main
    misc.init_distributed_mode(args)
  File "/ibex/user/slimhy/Shape2VecSet/code/util/misc.py", line 248, in init_distributed_mode
    torch.cuda.set_device(args.gpu)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 58737 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 58738 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 58739 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 58740 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 4 (pid: 58741) of binary: /home/slimhy/conda/envs/shape2vecset/bin/python3.10
Traceback (most recent call last):
  File "/home/slimhy/conda/envs/shape2vecset/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/slimhy/conda/envs/shape2vecset/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
code/main_node2node.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2023-11-07_20:33:27
  host      : gpu210-18.ibex.kaust.edu.sa
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 58742)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2023-11-07_20:33:27
  host      : gpu210-18.ibex.kaust.edu.sa
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 58743)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2023-11-07_20:33:27
  host      : gpu210-18.ibex.kaust.edu.sa
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 58744)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-07_20:33:27
  host      : gpu210-18.ibex.kaust.edu.sa
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 58741)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
